version: 2

models:
  - name: joined_crime_data  # The name of the model in dbt
    description: >
      This model joins the 'hote_crime' and 'major_crime' tables
      on 'EVENT_UNIQUE_ID', providing a comprehensive dataset
      with details about both hate crimes and major crimes,
      including various crime attributes such as date, division,
      location type, and neighbourhood data.
      
    columns:
      - name: EVENT_UNIQUE_ID
        description: Unique identifier for the event/crime occurrence.
        tests:
          - unique
          - not_null

      - name: OCCURRENCE_YEAR
        description: The year the crime occurred.
        tests:
          - not_null

      - name: OCCURRENCE_DATE
        description: The exact date the crime occurred.
        tests:
          - not_null

      - name: REPORTED_YEAR
        description: The year the crime was reported.
      
      - name: REPORTED_DATE
        description: The date the crime was reported.
      
      - name: HOTE_DIVISION
        description: Division assigned to the hate crime.
        
      - name: HOTE_LOCATION_TYPE
        description: The type of location where the hate crime occurred.
      
      - name: PRIMARY_OFFENCE
        description: The primary offence committed in the hate crime.

      - name: HOTE_HOOD_158
        description: The neighbourhood hood code for hate crime.

      - name: HOTE_NEIGHBOURHOOD_158
        description: The neighbourhood identifier for hate crime.

      - name: REPORT_DATE
        description: The date the major crime was reported.
      
      - name: OCC_DATE
        description: The date the major crime occurred.
      
      - name: REPORT_YEAR
        description: The year the major crime was reported.
        
      - name: REPORT_MONTH
        description: The month the major crime was reported.
        
      - name: REPORT_DAY
        description: The day of the month the major crime was reported.
        
      - name: REPORT_DOY
        description: The day of the year the major crime was reported.

      - name: MAJOR_CRIME_DIVISION
        description: Division assigned to the major crime.

      - name: MAJOR_CRIME_LOCATION_TYPE
        description: The type of location where the major crime occurred.
      
      - name: MAJOR_CRIME_OFFENCE
        description: The specific offence in the major crime.

      - name: MAJOR_HOOD_158
        description: The neighbourhood hood code for the major crime.

      - name: MAJOR_NEIGHBOURHOOD_158
        description: The neighbourhood identifier for the major crime.
