name: 'raw_nyc_tripdata'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  raw_nyc_tripdata:
    staging:
      +materialized: "view"
    core:
      +materialized: "table"

vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]

seeds: 
  raw_nyc_tripdata:
    taxi_zone_lookup:
      +column_types:
        locationid: "numeric"
